### ISSUE TITLE
Getting CCS for my PacBio Reads without a smrtanalysis environment

### ISSUE THREAD

**Issue by marcelauliano** [PacificBiosciences/pbccs#102]
Hey guys! 
I was trying to install pbccs in a computer cluster I use, but I found no setup.py or compile script inside it, so I guess I need to have smrtanalysis environment which contains other dependencies?

The thing is the cluster I'm using is a shared one, and the IT does not allowed me to install the environment locally due to tomcat start. So, until I get it installed it might take a while. So I was wondering if there is a way for me to get CCS for my subreads with a local script?

Thank you so much!

**Comment by mseetin** [comment]
Hi Marcela,

This program actually runs as a local script, but it cannot function without other core components, most notably bax2bam.  This program takes as input bam files, not the .bax.h5 files produced by the PacBio RSII, so it requires a conversion program to get the file format correct.  This capability won't be released publicly until Q1 2016 with the wide release of SMRT Analysis 3.0.

**Comment by nlhepler** [comment]
Hi Marcela,

As Matthew says, we're not yet in a place to support this outside the SMRTAnalysis environment. In particular, this new version of the CCS analysis is only available in the 3.0+ versions of SMRTAnalysis that have only been released as release-candidate/preview releases to early Sequel adopters. Again, as Matt says, we plan on opening these up to the wider world in Q1 2016.

I suspect some users don't want the hassle of a full environment, and would rather just have a bundle they could download locally and use for the command-line utilities within. Is this along the lines of what you're looking for?

In the meantime, I'm afraid we're not ready to tackle this issue.
