### ISSUE TITLE
Expose MaxIterations as a Command Line Parameter

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#121]
Currently hard coded at 40.

**Comment by nlhepler** [comment]
Yah I can do this real quick. I think we might want to ask Derek to support a --secrets option that exposes a bunch of knobs we don't normally want listed on the usual command-line, and a --secrets-help that exposes their usage/documentation text.

**Comment by pezmaster31** [comment]
Already in the upcoming parser:

    class Option {
    
    // ...

    /// \brief Sets whether to hide this option in the user-visible help output.
    ///
    /// All options are visible by default. Setting \a hide to true for a
    /// particular option makes it internal, i.e. not listed in the help output.
    ///
    Option& SetHidden(bool hide = true);

**Comment by pezmaster31** [comment]
I'd just need to add something to show them explicitly

**Comment by nlhepler** [comment]
@pezmaster31 I'd go a step further. Have these knobs unusable until you turn on another option (which dumps a message to the log too) so that they're aware they're tinkering in an unsupported fashion.

**Comment by nlhepler** [comment]
but I can always build on top of whatever you're doing. ;) Can't wait to play with the new API!!
