### ISSUE TITLE
Support dataset output directly

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbccs#137]
Presently in order to get a dataset XML out of CCS, we have to run 

``` sh
ccs in.subreadset.xml out.bam && \
 dataset create --type ConsensusReadSet out.consensusreadset.xml out.ccs.bam
```

It would be nice if we didn't have to do the DS creation manually:

`ccs in.subreadset.xml out.consensusreadset.xml`

`pbalign`, for example, already supports this

**Comment by armintoepfer** [comment]
#162
