### ISSUE TITLE
Compiling pbccs on mac

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/pbccs#138]
HI,

I am having some difficulty compiling the pbccs code on my mac.

When I run cmake, I get the following error message:

CMake Error at CMakeLists.txt:35 (find_package):
  Could not find a package configuration file provided by "htslib" with any
  of the following names:

    htslibConfig.cmake
    htslib-config.cmake

  Add the installation prefix of "htslib" to CMAKE_PREFIX_PATH or set
  "htslib_DIR" to a directory containing one of the above files.  If "htslib"
  provides a separate development package or SDK, be sure it has been
  installed.

Can you please help me troubleshoot this issue?

Thanks,
Charles

**Comment by evolvedmicrobe** [comment]
htslib is a dependency pbccs needs, you can get it from github via:

    git clone https://github.com/PacificBiosciences/htslib.git

Once you have it cloned to a directory, you can add a cmake flag to indicate where it is, e.g.

     -Dhtslib_DIR=/some_path/htslib

**Comment by dalexander** [comment]
See: https://github.com/PacificBiosciences/pbccs/blob/master/BUILD.md
