### ISSUE TITLE
ccs not loading chemistry list in pitchfork build

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbccs#145]
```
ccs 2.0.0 (commit 259e387)
ConsensusCore2 0.10.0 (commit ad508c2)
Copyright (c) 2014-2015 Pacific Biosciences, Inc.
License: 3-BSD
```

built with

```
$ gcc --version
gcc (GCC) 4.9.1
$ uname -a
Linux hgs4a 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
For some reason when I build ccs with pitchfork it doesn't seem to recognise the P6-C4 chemistry. I tweaked the error message with PR #144 and got the following.

```
>|> 20160516 11:17:38.078 -|- DEBUG      -|- main -|- 0x7f3dccc66740|| -|- Found consensus models for: ()
>|> 20160516 11:17:38.082 -|- FATAL      -|- main -|- 0x7f3dccc66740|| -|- Unsupported chemistries found: "P6-C4" Supported chemistries are: ""
```

Curiously I could not reproduce this error when I built this manually rather than using pitchfork.

**Comment by dalexander** [comment]
> Curiously I could not reproduce this error when I built this manually rather than using pitchfork.

This is bizarre.

**Comment by nlhepler** [comment]
This is because of the absence of [various flags](https://github.com/PacificBiosciences/ConsensusCore2/blob/master/CMakeLists.txt#L74) needed to have the compiler/linker not optimize the models away as dead code. I have no idea why the pitchfork build would break this.

**Comment by mp15** [comment]
I'll have another go from a clean checkout, see if I can reproduce reliably. I take it that putting __attribute__((used)) on the pertainant functions doesn't work?

**Comment by mp15** [comment]
Built from clean pitchfork checkout, reproduced the error.

**Comment by nlhepler** [comment]
https://github.com/PacificBiosciences/pitchfork/blob/master/ports/pacbio/pbccs/Makefile#L29 This is the offending line

**Comment by mhsieh** [comment]
can @mp15 give it a test?

**Comment by mp15** [comment]
Will give it a test tomorrow

**Comment by mp15** [comment]
@mhsieh Retested and this works now.

Might be worth considering making ConsensusCore2 a shared library on all platforms if you want to continue using this design pattern. I looked into alternatives and the only other proper way to deal with it (without the full archive `ld` command) would be with a `__attribute__((section()))` with a linker script and KEEP sections but that's not very portable.

**Comment by mhsieh** [comment]
Yes, that's exactly what I modified.
