### ISSUE TITLE
alpha/beta mismatch error

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbccs#146]
I have getting the following errors on the SKBR3 MHC pulldown cell line data:

````
>|> 20160516 15:40:16.095 -|- ERROR      -|- operator() -|- 0x7f51db9a2700|| -|- Skipping m150517_204412_sherri_c100800262550000001823168409091511_s1_p0/101288, caught exception: 'alpha/beta mismatch error!'
>|> 20160516 15:57:27.848 -|- ERROR      -|- operator() -|- 0x7f51cf98a700|| -|- Skipping m150517_204412_sherri_c100800262550000001823168409091511_s1_p0/148755, caught exception: 'alpha/beta mismatch error!'
````

I have grep'd put the source reads for the first error listed into a gist at: https://gist.github.com/mp15/8a7000c8afebe073f71603ce23d35e3c

**Comment by evolvedmicrobe** [comment]
Hi @mp15 - Thanks for pull request earlier today!

Regarding these A/B mismatch errors - we typically expect a few of these to occur in every run, and they are indicative of bad data.  For example, the gist you gave with some of the subreads shows that many of them had long runs of identical/similar bases.  These can be indicative of DNA damage to one of the basepairs in the strand, or some other oddity that occurs.  These mismatches should occur somewhat infrequently though, so probably best to check that the number isn't too high.  At the end of the CCS run, you should see a "Subread Yield" report, can I ask what the percentage listed next to "Alpha/Beta mismatch" was?

**Comment by mp15** [comment]
Hi @evolvedmicrobe,

I suspect these two errors are actually the ones listed below as: `Failed -- Unknown error during processing,2,0.00%` rather than `Failed -- Alpha/Beta mismatch,240,0.16%`. I am curious as to what is causing these alpha/beta mismatches are getting handled via an exception causing an error log rather than them being a mere statistic. Perhaps we could just suppress the error message, given that this is not really an error?

```
ZMW Yield
Success -- CCS generated,4320,6.14%
Failed -- Below SNR threshold,9690,13.77%
Failed -- No usable subreads,5151,7.32%
Failed -- Insert size too long,41,0.00%
Failed -- Insert size too small,0,0.00%
Failed -- Not enough full passes,51117,72.66%
Failed -- Too many unusable subreads,30,0.04%
Failed -- CCS did not converge,35,0.05%
Failed -- CCS below minimum predicted accuracy,4,0.01%
Failed -- Unknown error during processing,2,0.00%


Subread Yield
Success - Used for CCS,24664,16.64%
Failed -- Below SNR threshold,21898,14.78%
Failed -- Alpha/Beta mismatch,240,0.16%
Failed -- Below minimum quality,3135,2.12%
Failed -- Filtered by size,14588,9.84%
Failed -- Z-Score too low,1717,1.16%
Failed -- From ZMW with too few passes,80407,54.26%
Failed -- Other,1528,1.03%
```

**Comment by nlhepler** [comment]
@mp15, it's just an anomaly in reporting: subreads can be filtered out by A/BMs, but sometimes a ZMW will fail processing during polishing because a read is just on the edge of A/BM and the polishing step pushes it over. I'm working on a patch to address this case. But it seems like things are working as expected here, so I'm going to go ahead and close this issue.
