### ISSUE TITLE
byStrand,noPolish settings incorrectly recognized as true by ccs under clang

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbccs#149]
See: https://gist.github.com/dalexander/1dcad856f6910479aafd712c52736541

**Comment by dalexander** [comment]
Fix in #150

**Comment by evolvedmicrobe** [comment]
Wow, just wow.  

> "When your code is too clever to be compiled reliably, it's a sign that you need to dumb down your code." 

Couldn't agree more
