### ISSUE TITLE
Errors installing on OSX

### ISSUE THREAD

**Issue by jonathandmoore** [PacificBiosciences/pbccs#152]
Cluster installation bogged down in errors, so trying laptop instead OSX El Capitan 10.11.5.  Errors all round here as well, any ideas welcome.

With pitchfork, I am stuck here:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/zlib provided
rm -rf /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8
mkdir -p /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/include
mkdir -p /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/lib
cp -a [ERROR] /usr/include/zlib.h missing, check your HAVE_ZLIB value/include/zlib.h [ERROR] /usr/include/zlib.h missing, check your HAVE_ZLIB value/include/zconf.h /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/include/
cp: [ERROR]: No such file or directory
cp: /usr/include/zlib.h: No such file or directory
cp: missing,: No such file or directory
cp: check: No such file or directory
cp: your: No such file or directory
cp: HAVE_ZLIB: No such file or directory
cp: value/include/zlib.h: No such file or directory
cp: [ERROR]: No such file or directory
cp: /usr/include/zlib.h: No such file or directory
cp: missing,: No such file or directory
cp: check: No such file or directory
cp: your: No such file or directory
cp: HAVE_ZLIB: No such file or directory
cp: value/include/zconf.h: No such file or directory
make[1]: *** [provided] Error 1
make: *** [zlib] Error 2

With the 'manual' dependencies way, I am stuck here:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
-- Boost version: 1.60.0
CMake Error at CMakeLists.txt:27 (find_package):
  Could not find a package configuration file provided by "htslib" with any
  of the following names:

    htslibConfig.cmake
    htslib-config.cmake

  Add the installation prefix of "htslib" to CMAKE_PREFIX_PATH or set
  "htslib_DIR" to a directory containing one of the above files.  If "htslib"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by evolvedmicrobe** [comment]
For the manual installation, try removing the readlink option in the cmake flag so your command looks like below.

     $ cmake                                               \
           -DSEQAN_INCLUDE_DIRS=../_deps/seqan/include       \
           -DPacBioConsensus_RootDir=../_deps/ConsensusCore2 \
           -DPacBioBAM_RootDir=../_deps/pbbam                \
           -DHTSLIB_ROOTDIR=../_deps/htslib    \
           ..

**Comment by jonathandmoore** [comment]
Thanks, that has removed the readlink error.  I still have the find_package error for htslib.

**Comment by jonathandmoore** [comment]
I got past the find_package error by setting an environment variable, but now I am here:

CMake Error at _deps/ConsensusCore2/cmake/FindGitSha1.cmake:17 (message):
Could not determine git sha1 via `git describe --always --dirty=*`

**Comment by nlhepler** [comment]
Take a look [here](https://github.com/PacificBiosciences/pitchfork/blob/master/settings.mk.example) and make sure you do the xcode-select step. You'll need a zlib.h include file somewhere to successfully build htslib.

For the git error, do you have git installed and available in your PATH?

**Comment by jonathandmoore** [comment]
Thanks, xcode-select helped stop one error.  Next one is:
/Users/moorej/Downloads/pbccs-master/pitchfork/bin/pitchfork fetch --url http://cython.org/release/Cython-0.23.4.tar.gz
fetching http://cython.org/release/Cython-0.23.4.tar.gz
md5sum -c MD5SUM || exit
md5sum: stat 'Cython-0.23.4.tar.gz': No such file or directory
tar zxf Cython-0.23.4.tar.gz -C /Users/moorej/Downloads/pbccs-master/pitchfork/workspace
tar: Error opening archive: Failed to open 'Cython-0.23.4.tar.gz'
make[1]: *** [/Users/moorej/Downloads/pbccs-master/pitchfork/workspace/Cython-0.23.4] Error 1
make: *** [cython] Error 2


I am not getting any response from cython.org - is this still the right address?



I do have git installed and in my $PATH:
git --version
git version 2.7.4 (Apple Git-66)

**Comment by nlhepler** [comment]
Huh, we don't need Cython for pbccs, could you try `make pbccs` from your pitchfork root directory?

**Comment by jonathandmoore** [comment]
Yes, that was what I did.  Trying it again, and it's fetching http://cython.org/release/Cython-0.23.4.tar.gz again and failing.  Here's the full shell output:

make pbccs
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/ccache do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/zlib provided
rm -rf /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8
mkdir -p /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/include
mkdir -p /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/lib
cp -a /usr/include/zlib.h /usr/include/zconf.h /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/include/
cp -a /usr/lib/libz.*                              /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/lib/
mkdir -p /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/lib/pkgconfig
find /usr/lib -name 'zlib.pc' -exec cp -a {} /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/lib/pkgconfig/ \;
cd /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8 && tar cf - * | tar xf - -C /Users/moorej/Downloads/pbccs-master/pitchfork/deployment
find /Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8 ! -type d|awk -F '/Users/moorej/Downloads/pbccs-master/pitchfork/staging/zlib-1.2.8/' '{print $2}' > /Users/moorej/Downloads/pbccs-master/pitchfork/deployment/var/pkg/zlib-1.2.8
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/samtools do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/cmake do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/boost do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/pacbio/htslib do-install
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/moorej/Downloads/pbccs-master/pitchfork/workspace/htslib \
                   CC=gcc \
            ZLIB_ROOT=/Users/moorej/Downloads/pbccs-master/pitchfork/deployment \
               CFLAGS="-fPIC -I/Users/moorej/Downloads/pbccs-master/pitchfork/deployment/include -Wall -O2 -Wno-unused-function" \
              LDFLAGS="-Wl,-rpath,'RIGIN/../lib',-rpath,'$ORIGIN/../lib' -L/Users/moorej/Downloads/pbccs-master/pitchfork/deployment/lib" \
        >& build.log || /Users/moorej/Downloads/pbccs-master/pitchfork/bin/diewith build.log
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/thirdparty/gtest do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/pacbio/pbbam do-install
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/moorej/Downloads/pbccs-master/pitchfork/workspace/pbbam/build
[ 80%] Built target pbbam
[ 84%] Built target bam2sam
[ 89%] Built target pbindex
[ 96%] Built target pbindexdump
[100%] Built target pbmerge
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ports/pacbio/seqan do-install
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j1 -C ports/python/virtualenv do-install
/usr/bin/python
make[1]: Nothing to be done for `do-install'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j1 -C ports/python/cython do-install
/Users/moorej/Downloads/pbccs-master/pitchfork/bin/pitchfork fetch --url http://cython.org/release/Cython-0.23.4.tar.gz
fetching http://cython.org/release/Cython-0.23.4.tar.gz
md5sum -c MD5SUM || exit
md5sum: stat 'Cython-0.23.4.tar.gz': No such file or directory
tar zxf Cython-0.23.4.tar.gz -C /Users/moorej/Downloads/pbccs-master/pitchfork/workspace
tar: Error opening archive: Failed to open 'Cython-0.23.4.tar.gz'
make[1]: *** [/Users/moorej/Downloads/pbccs-master/pitchfork/workspace/Cython-0.23.4] Error 1
make: *** [cython] Error 2

**Comment by nlhepler** [comment]
Let's close this here and open it on pitchfork, which is where the real problem is. This project is just for the pbccs application itself, whereas pitchfork has another maintainer who will have to get involved.

**Comment by jonathandmoore** [comment]
OK I might track the pitchfork issue.  Any ideas why I'm getting the git error if I try to install pbccs without pitchfork?  git seems functional enough on its own.

**Comment by nlhepler** [comment]
What happens if you run `git describe --always --dirty=*` inside your build directory?

**Comment by nlhepler** [comment]
Sorry, inside the pbccs project directory?

**Comment by jonathandmoore** [comment]
I get this:
fatal: Not a git repository (or any of the parent directories): .git
