### ISSUE TITLE
minPasses < 1

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbccs#153]
Edward Oakeley would like to use CCS to perform raw subread polishing. We always talk that this is possible, but until we can set minPasses <1 pbccs can't be used for this as it really destroys yield for genomic library preps. So let's drop this threshold. Also, Jim Bullard might be happier too.

**Comment by evolvedmicrobe** [comment]
@nlhepler This is completed right?

**Comment by nlhepler** [comment]
yes
