### ISSUE TITLE
Unsupported Sequencing Chemistry Combination / Where to find model files?

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/pbccs#166]
Hi,

I am actually trying to use `ccs` in unanimity, but I didn't see an issue listing on that site and I get the same error message if I try use the the pbccs version of `ccs`.

I am trying to define CCS reads from the following sample:

http://www.ebi.ac.uk/ena/data/view/ERX1417672

I've run `bax2bam` to create an unaligned bam file, but I get the following error message if I try to run `ccs` to create CCS reads:

```
>|> 20170427 00:21:47.414 -|- FATAL      -|- main -|- 0x7f258e839740|| -|- unsupported sequencing chemistry combination: 
    binding kit:        100236500
    sequencing kit:     001558034
    basecaller version: 2.1.0.0.127824
```

(the error message in the later unanimity version is similar, but says "Runner" instead of "main")

In the unanimity version, there are `--modelPath` and `--modelSpec` parameters.  The ENA listing says that P4C2 chemistry was used, but neither "P4-C2" or "P4C2" works for --modelSpec.  So, I was thinking about using the --modelPath parameter, but I don't know where to find the file to specify with that parameter.

Can you please help me troubleshoot CCS read generation for this sample?

Thanks,
Charles

**Comment by mseetin** [comment]
Hi Charles,

P4C2 is very old. It is not currently supported for use with ccs2, and I
would doubt that support would ever be added.

**Comment by cwarden45** [comment]
OK - I was able to define CCS reads using CircularConsensus from ConsensusTools.sh in SMRTportal 2.3.0
