### ISSUE TITLE
Issues Installing pbccs

### ISSUE THREAD

**Issue by MerillaM** [PacificBiosciences/pbccs#167]
I'm trying to install pbccs using pitchfork and am running into issues when it tries to install unanimity. I get the following error message:

`[ 24%] Building CXX object src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o
In file included from /opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:45:0,
                 from /opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:52,
                 from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:46:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:132:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::NCBI4naToNCBI2naImpl(uint8_t)’:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:175:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
In file included from /opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:52:0,
                 from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:46:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h: At global scope:
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na::FromASCII(65, 1)’
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))’
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’ called in a constant expression
         : data_{ASCIIToNCBI4naImpl(base, checkValid)}
                                   ^
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of ‘PacBio::Consensus::TemplatePosition(65, 1.0e+0, 0.0, 0.0, 0.0)’
/opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:89:40:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na::FromASCII(((int)((PacBio::Consensus::TemplatePosition*)this)->PacBio::Consensus::TemplatePosition::Base), 1)’
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))’
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’ called in a constant expression
In file included from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:54:0:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:88:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char, uint8_t)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:105:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr std::pair<char, unsigned char> PacBio::Consensus::{anonymous}::DecodeEmission(uint8_t)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:130:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
src/CMakeFiles/cc2.dir/build.make:326: recipe for target 'src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o' failed
make[4]: *** [src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o] Error 1
make[4]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/cc2.dir/all' failed
make[3]: *** [src/CMakeFiles/cc2.dir/all] Error 2
make[3]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:48: recipe for target '/opt/pitchfork/workspace/unanimity/_build/ccs' failed
make[1]: *** [/opt/pitchfork/workspace/unanimity/_build/ccs] Error 2
make[1]: Leaving directory '/opt/pitchfork/ports/pacbio/unanimity'
Makefile:402: recipe for target 'unanimity' failed
make: *** [unanimity] Error 2`

**Comment by SoapZA** [comment]
This repository is deprecated and unmaintained
