### ISSUE TITLE
Do actual chemistry decoding (rather than a check for P6/C4-ness)

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbccs#23]

**Comment by evolvedmicrobe** [comment]
@nlhepler I am going to dump some quick code in now to remove the hard coded "P6-C4".  I saw there was some XML parsing foreshadowed here, so will expect it all to be removed later.

**Comment by nlhepler** [comment]
Works for me, at least as a temporary measure

**Comment by evolvedmicrobe** [comment]
@nlhepler have we closed this now?

**Comment by nlhepler** [comment]
Yes
