### ISSUE TITLE
Recover good data sections from bad subreads

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#38]
Right now if any stretch of a subread looks very bad, the entire subread is dropped.  For example consider the following:

```
GATCATACGATAGCCGTACCTGACATAGAGACATTA  <- Insert
GATCATACGATA-----------CATAGAGACATTA  <- Subread
```

Because the subread shown has an unexplained and large deletion in the middle, we drop the whole read.  This improves overall quality (the center section would otherwise vote for deletions), but at the expense of losing information at the tails where there actually seems to be good data present.  For small inserts, given the rarity of these events this is an acceptable yield loss.  However, for larger inserts where the a stretch of "funky" data might be more likely to be encountered somewhere along the subread, we may increase yield and accuracy by recovering these good sections while excluding the bad.

This is currently a low priority enhancement.

**Comment by nlhepler** [comment]
Maybe it didn't. Maybe the polymerase slipped

**Comment by evolvedmicrobe** [comment]
Which goes back to your comment about affine indel.

**Comment by nlhepler** [comment]
Yea, though it's not going to be fun to implement or to listen to people complain about performance...

**Comment by nlhepler** [comment]
Well, might be fun to implement if we can leave more legacy stuff behind. I want to kind of do a semi-rewrite where we start with nothing and pull in classes/functions/methods 1-at-a-time, cleaning up each one, until we have a minimal working configuration.

**Comment by dalexander** [comment]
Let's ask MBrown if he can help us inspect some of these in PulseRecognizer early next week.
