### ISSUE TITLE
Passthrough TagCollection for things like barcode assignments

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbccs#41]

**Comment by dalexander** [comment]
yes

**Comment by evolvedmicrobe** [comment]
Just talked about this with Brett.  So, the challenge is what to do when the barcodes don't match within a zmw.  We decided that we will emit a UINT.MAXVALUE for this case, let me know if there are any complaints.

**Comment by evolvedmicrobe** [comment]
Just committed f0b58ad with ability to pass through barcodes and tests to verify, closing isssue.

**Comment by nlhepler** [comment]
I don't know if I'm on board with this ... I'd much rather have it go through bam2bam for rebarcoding ... the case you describe above requiring UINT.MAXVALUE is a telltale sign that this passthrough is not necessarily well-formed, there could be pathological cases where a huge number of ZMWs are labeled thusly.

**Comment by evolvedmicrobe** [comment]
@bnbowman can comment on the feasibility, I was not aware that bam2bam could add barcodes to a ccs.bam file.  How does it adjudicate when the same ZMW has different barcodes called by the adapters?

**Comment by nlhepler** [comment]
There's also the problem of the LocalContextFlags, which are not necessarily passed through here, in particular BARCODE_BEFORE and BARCODE_AFTER.

**Comment by nlhepler** [comment]
We would just use the CCS to recall the barcodes, not the constituent subreads. The CCS is an entirely different beast, a completely novel sequence generated from the subreads. While it might be true sometimes, or even often, the properties of the subreads do not necessarily perpetuate into the CCS. Some concepts, like queryStart and queryEnd, for example, are not provided. I would advocate that most (if not any) kind of "downstream" sequencing analysis done on the subreads (such as barcode calling) must be redone for the CCS separately.

**Comment by nlhepler** [comment]
I would also really, really like to dissuade everyone from on-the-fly specification-making as in the case of the UINT.MAXVALUE -- it leads to the implementation leading ahead of the specification, essentially creating undocumented behavior. If this is really deemed the best way to address this problem, please update https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst as well

**Comment by evolvedmicrobe** [comment]
The barcode sequences are not in the input.bam that CCS takes, but in a separate index file based on my conversation with Brett.  I am strongly against having CCS take a dependency on another file which is not guaranteed to be present or in sync with the input file.  People always have the option to ignore the bc tags, the output is identical except for the addition of these fields.

But we should probably define the problem better before discussing more.  Right now, there are no "downstream" sequencing analysis tools that use CCS barcodes or any consumer save Brett, so any discussion is ungrounded and academic.   Brett asked for the feature so I dropped it in, but I know you created the original issue.  What were you thinking was the point of these tags and who would use them?

**Comment by evolvedmicrobe** [comment]
The BAM fileformats have only a passing mention of ccs.bam files, the whole thing is undocumented (e.g. look at the QUAL field description here: https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst)... we need to fix that.

**Comment by nlhepler** [comment]
A user intending on using barcodes with CCS should probably instead provide the barcode sequences as a separate, downstream analysis step from CCS generation (and bam2bam should do the trick, @bnbowman can speak to whether this makes sense). When I opened the issue originally, it didn't immediately occur to me what to do about the mixed barcode case, or that this even made sense. Now that you've gone ahead and implemented it, it's clear there are some issues wrt to providing a first-class barcoding experience with CCS--yanking the data from the subreads is not necessarily a well-formed operation, and things like BARCODE_BEFORE and _AFTER do not translate. I'm not advocating that we automatically rebarcode for the user (requiring the gross dependency, as you say, but barcoding in general has this problem and it is not unique to CCS). It might perhaps be sufficient to just leave the user a message that we detected and are discarding barcoding data, and that the CCS sequences will need to be reanalyzed using bam2bam.

**Comment by nlhepler** [comment]
@evolvedmicrobe, wrt to QUAL values, we absolutely, most definitely should.

**Comment by bnbowman** [comment]
I have multiple reasons for wanting to pass-through barcode information:
1). Simplicity - this way I only need one model for calling / scoring
barcodes
2) Chimera filtering - planned feature comparing barcodes across a ZMW to
catch 2P sequences, which I can't do on CCS
3). Clashing namespace - BC and BQ tags would then have two meanings,
discordant with other barcoding results / data
4).  Breaks the PPA model - barcoding is now supposed to be an upstream
prepossessing step a la adapter finding

**Comment by nlhepler** [comment]
1) Fair enough, though a test as to whether the preexisting model suffices for CCS could obviate this concern.
2) I don't think it's fair that the existence of an inapplicable analysis should count for or against.. you have the problem either way..?
3) I don't understand this point. We would just re-barcode the CCS sequences and populate the correct LocalContextFlags. To what double meaning are you referring?
4) This is perhaps the best point so far, but bam2bam was already put into place for dealing with scenarios such as this. "Supposed to be" shouldn't interfere with doing things the correct way.

**Comment by evolvedmicrobe** [comment]
I agree with Brett's concern about the BQ/BC tags, it's a general problem... CCS and raw reads have a lot of similarities in terms of metrics, but they aren't exactly the same so it's confusing to give them the same label at times.  But that's not what's preventing everyone from using our awesome instrument right now.

It sounds like we have no actual external use case for these yet, but they could be valuable for R&D.  There are other BAM tags this applies to, e.g. the "mt", "ma", "ms" tags, and I have been wanting to put in a TAG that gives "RQ" as the error probability, rather than 1 minus that probability to maintain precision.

So how about this, for this bc tag and the others which at present only are consumed by R&D, we only generate them if pbccs is compiled with a special flag, that way we have them for R&D but they don't go into the release build.  We could then revisit that decision whenever we have a defined use case that could actually affect or benefit a customer.  Thoughts?

**Comment by nlhepler** [comment]
I can get behind this plan of action 100%

**Comment by bnbowman** [comment]
>3) I don't understand this point. We would just re-barcode the CCS
sequences and populate the correct LocalContextFlags.

I don't see the CX tag as relevant to this discussion - it is a
subread-specific tag, not a ZMW-specific tag, so it implies nothing about
BC/BQ other than their existence.  So passing through BC and BQ but not CX
is perfectly reasonable.

Or in a practical example - the CX tag on the first subread can refer to a
condition where it has a single barcode on one side, and that one barcode
may be a reverse-sided barcode.  But the BC tag for that same subread will
have both the Forward and Reverse barcodes, and in the F--R orientation.

>To what double meaning are you referring?

BC and BQ tags being calculated by two different algorithms for Raw/CCS
data, and therefore potentially having different problems / ranges /
behaviors.

>4) This is perhaps the best point so far, but bam2bam was already put into
place for dealing with scenarios such as this. "Supposed to be" shouldn't
interfere with doing things the correct way.

Bam2bam does not understand CCS files, or even single BAM files (absent the
LQ/Scraps partner file).  This would require a completely new code-path.

**Comment by bnbowman** [comment]
>So how about this, for this bc tag and the others which at present only
are consumed by R&D, we only generate them if pbccs is compiled with a
special flag,

That should suffice for now.

**Comment by evolvedmicrobe** [comment]
https://github.com/PacificBiosciences/pbccs/pull/90/files
