### ISSUE TITLE
Decide if we should enable a by-pass for long/low-coverage data

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#42]
From Liz.

Version/build when this occurred: 0.0.1 (internal build)

Overview: new CCS is very slow. A single movie (three .bax.h5 combined to a bam
file) takes almost a day to finish on 12 CPUs.

Steps to reproduce

directory:
/home/UNIXHOME/etseng/projects2015/internal_Ting_Maize/smrtpipe/BC_rerun_4to6kb_newCCS

The .bax.h5 files were first converted bam per movie (see: bax2bam.sh)

Then CCS was called using the following parameters:

`ccs --minLength 300 --minPasses 0 --minPredictedAccuracy 0.75 --numThreads 12
--minZScore -999999 --maxDropFrac 1.0`

NOTE: the ridiculous minZScore and maxDropFrac are intentional. We are trying
to get as much CCS as possible to look at some stats.

Each ccs job is submitted to SGE (ex: qsub -pe smp 12 cmd_1).

I did not explicitly time since I didn't know that was going to be an issue,
but the jobs were all submitted (and started) on Aug 5 2PM.

You can look at the <movie>.ccs.report timestamp to see when it finished.

Aug  7 05:32
m150520_052201_42141_c100722061910000001823149204301510_s1_p0.ccs.report
Aug  7 03:41
m150520_140510_42141_c100722061910000001823149204301512_s1_p0.ccs.report
Aug  6 13:42
m150520_234644_42141_c100722061910000001823149204301513_s1_p0.ccs.report
Aug  6 08:12
m150521_040756_42141_c100722061910000001823149204301514_s1_p0.ccs.report
Aug  6 19:08
m150521_083055_42141_c100722061910000001823149204301515_s1_p0.ccs.report
Aug  6 13:42
m150521_125225_42141_c100722061910000001823149204301517_s1_p0.ccs.report

So some of the took about a day and two of them took 1.5 days.

**Comment by nlhepler** [comment]
I know why this is slow. Look at the --minPasses option. The old CCS didn't propagate everything forward. The new CCS does the right thing wrt to the QVs, but this would mean everything takes forever.

**Comment by evolvedmicrobe** [comment]
![image](https://cloud.githubusercontent.com/assets/1330626/9148422/e270b42c-3d2f-11e5-8500-d2d7d9be1767.png)

Yikes.. check out the per subread read Z-score distribution for this dataset, it's all over the place.

**Comment by nlhepler** [comment]
Yowzers, what's with the bimodality?

**Comment by evolvedmicrobe** [comment]
No idea, maybe @etseng knows?  But It looks like your theory is right on.  Most of these reads are coverage = 1 and super long.  From profiling before these take up a ton of time, and were never handled properly in the old version.


![image](https://cloud.githubusercontent.com/assets/1330626/9148479/3187a514-3d32-11e5-9ae7-b55fb4ce10ff.png)

**Comment by nlhepler** [comment]
Ohhhh, for 0- and 1-pass ZMWs the model will perfectly match the observations, leading to super-high z-scores.

**Comment by nlhepler** [comment]
As a test, what does the z-score distribution look like for all np:i:2?

**Comment by evolvedmicrobe** [comment]
Here's a little geom jitter and density for you:

![image](https://cloud.githubusercontent.com/assets/1330626/9148542/a85cf1f6-3d34-11e5-82d1-4e09d3f8ba38.png)

So the Avg is approaching the mean as it should, but I don't understand completely how you get such low Za values at NP=0/1.

Focusing on the distribution of  Z scores for reads with 5X coverage, it starts to look a lot more normal (but still possibly over-dispersed).


![image](https://cloud.githubusercontent.com/assets/1330626/9148577/f81b2cac-3d35-11e5-970d-321ea53bf5d9.png)

**Comment by evolvedmicrobe** [comment]
violin probably clearer

![image](https://cloud.githubusercontent.com/assets/1330626/9148593/660ed70e-3d36-11e5-923c-f60c39204078.png)

**Comment by nlhepler** [comment]
This suggests there might be a bug in the POA--I'll file a bug against that to write some unit tests for single-string POAs -- seq == POA(seq), and AlignmentSummary should have end-to-end start/end. That could cause some low z-scores, maybe.

As for over-dispersion, ~ shrug ~ ? Real data isn't generated according to our model exactly...

**Comment by evolvedmicrobe** [comment]
Yeah, I suppose if the likelihood is low due to some bug, it will take a long time to get to the right answer... we should probably verify the speed/POA are acceptable, gonna assign to the POA expert if that's alright.

**Comment by pb-jchin** [comment]
just a general question, is the z-score a new and calibrated one? or is it inherited from long time ago?

**Comment by dalexander** [comment]
Hi Jason, this has nothing to do with the alignment Z-scores from BLASR

**Comment by pb-jchin** [comment]
@dalexander that is good :)

**Comment by evolvedmicrobe** [comment]
oh, blasr has Z-scores???  What are those?  

Jason, I will send you the write up on these Z-scores.

**Comment by nlhepler** [comment]
Nigel, I'm going to make a new issue for the POA bits, and unassign myself here.

**Comment by evolvedmicrobe** [comment]
Referencing [Bug 28985] on the internal system.

**Comment by evolvedmicrobe** [comment]
Added bypass to use noPolish option.
