### ISSUE TITLE
Nightly Build Still Has Z-Score Default of -2

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#43]
We have been getting complaints about dropped reads due to Z-Score filtering, it appears to be the case that the nightly build still has a Z-score default of -2 and not -5, leading to the drastic yield loss.

**Comment by nlhepler** [comment]
Hmm, that's weird, because pivc had pbccs at d03a8ce849fdee1580b58f9b4832b02e51d0e37a, which has the -5 cutoff. Also, the latest build's `ccs --help` shows the default value as -5, and that stuff doens't lie.

**Comment by evolvedmicrobe** [comment]
So jharting ran this command on or about Aug 5-6

    /mnt/secondary/builds/full/3.0.0/prod/current-build_smrtanalysis/smrtcmds/bin/ccs --minLength=700 --minPasses=1 --reportFile=ccs.filtered.report.csv cell1.ccs.filtered.bam cell1.subreads.bam

And the highest non-NaN value is:

    > min(d$ZScore[!is.na(d$ZScore)])
    [1] -1.999999

And I am thinking this may apply to other people.  Can we figure out who needs to re-run the data somehow? (When did the -5 get checked in?)

**Comment by nlhepler** [comment]
Now that is really convincing. Okay, I'll go digging. The checkin was ages ago, last Friday. This suggests something else is up.

**Comment by evolvedmicrobe** [comment]
I'm looking at a file he ran with Zscore=-6 right now to see what that looks like to.

**Comment by nlhepler** [comment]
https://github.com/PacificBiosciences/pbccs/blob/master/include/pacbio/ccs/Consensus.h#L93

and

https://github.com/PacificBiosciences/pbccs/blob/master/include/pacbio/ccs/Consensus.h#L400

and 

https://github.com/PacificBiosciences/pbccs/blob/master/ConsensusCore/src/C%2B%2B/Arrow/MultiReadMutationScorer.cpp#L313

Show the default to be -5, and to be properly passed through. Thoughts?

**Comment by evolvedmicrobe** [comment]
hold on, this might be a file copy issue..

**Comment by evolvedmicrobe** [comment]
grr wrong path to output file 

    > min(d$ZScore)
    [1] -4.996608
