### ISSUE TITLE
Tests for POA edge-case(s) (single-read mostly)

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbccs#45]

**Comment by evolvedmicrobe** [comment]
We should probably just pass the read through the POA in the case the case of one read and make it the initial template.  I think it gets dodgy when we have one read from the back half and another read from the front half of a template.

**Comment by evolvedmicrobe** [comment]
@lhepler the BAM file at: 

/home/UNIXHOME/ndelaney/smallProjects/etseng/badZ.bam 

Contains one ZMW that was dumped with a really bad z-score based on two subreads.  CCS was run with the following options

      -minZScore=-500000 --maxDropFraction=1 --minPredictedAccuracy=0 --minPasses=0

Everything from POA to Consensus seems pretty broken, and the Z-scores are both super low (-5.47436, -3.8087).

     INITIAL POA            TATGTGTAATATAGCTCTCTTGTGCCGCCCAGTTTGTCGATCTCAGGTCAAGCTCAAGGATTGTTTAATGGCCACTGACAAAAGGTTACAACAGTTGCATCATTAACTGTGGCATGTAAAACCTGCCCCCTTCTGTTGATGCATAAAATCCACCAATAGAGGAAGATTCTTCCGTCAAGAATATAGGGTCTGGACTGATTACTATTTCTCGTAAATGCCGCAGCAGTTTCCAATCATAACAAACAAAAGGCCAAGCTTAGTAAGTACATAGATAAGCCCAATACTTTTGTGAAACCTGCCATAGCTAACAGAGAAATCATCCTGGAATCTGGGGGAAGTAGAGTCGGCTTGTTTCTTGAAAAACCAGGTTCCCTGGCATGTGACCAGTTAATAACATGAACTTTGAAGTGATCTGGTCCAGCATAGTTGTCTTTTGAGGCGAACAAATAGGGTTGATGGATTCTCATTACCAACACCTTAAATGTTGCAAAAGCGCTGCATGGGCTTCGAAGTGTCCTGGCCTACGTTTTGATGCAATCAGAAAAAGTTGCATATTCACGGCAGAACCCAGGAGGTAGATCGGGACCGGCGGGGTGCCCAGTTGGTACTCTGGCGGTAGTCTTCGAGTGCCTTTCCGGCCTGGGT
     READ 1                                                                                                                                                                                                                                            																																				  CAGCTGATCGCTATACCAGCCCTTATCTAGCCTTCTCTCAGCAGTGTCGACAGACCGAAACCAGAGCTGCGGATATGCGATTGCTATCTCATCCCCACAACCAACTTATTGCACAAGACGCGCCCAGGGATCTCCTAGCTGGCGTAATATGGCCTGGCTACGTTGTTTGCATCAACAAGGAAAGTTGCATATTCACGGCAGAACCCAGGAGGTAGATCGGGACCGGCGGGGTGCCCAGTTGGTACTCTGGCGGTAGTCTTCGAGTGCCTTTCCGGCCTGGGT
     READ 2 (RevComp)       TATGTGTAATATAGCTCTCTTGTGCCGCCCAGTTTGTCGATCTCAGGTCAAGCTCAAGGATTGTTTAATGGCCACTGACAAAAGGTTACAACAGTTGCATCATTAACTGTGGCATGTAAAACCTGCCCCCTTCTGTTGATGCATAAAATCCACCAATAGAGGAAGATTCTTCCGTCAAGAATATAGGGTCTGGACTGATTACTATTTCTCGTAAATGCCGCAGCAGTTTCCAATCATAACAAACAAAAGGCCAAGCTTAGTAAGTACATAGATAAGCCCAATACTTTTGTGAAACCTGCCATAGCTAACAGAGAAATCATCCTGGAATCTGGGGGAAGTAGAGTCGGCTTGTTTCTTGAAAAACCAGGTTCCCTGGCATGTGACCAGTTAATAACATGAACTTTGAAGTGATCTGGTCCAGCATAGTTGTCTTTTGAGGCGAACAAATAGGGTTGATGGATTCTCATTACCAACACCTTAAATGTTGCAAAAGCGCTGCATGGGCTTCGAAGTGTCCTGGCCTACGTTTTGATGCAATCAGAAAAAGTTGCATATCCCTTCACAGTTGTGGCCCCAGTTACTCTGCGTTAGATACACTTGCTTT
     Consensus 			          AGCTCAAGGATTGTTTAATGGCCACTGACAAAAGGTTACAACAGTTGCATCATTAACTGTGGCATGTAAAACCTGCCCCCTTCTGTTGATGCATAAAATCCACCAATAGAGGAAGATTCTTCCGTCAAGAATATAGGGTCTGGACTGATTACTATTTCTCGTAAATGCCGCAGCAGTTTCCAATCATAACAAACAAAAGGCCAAGCTTAGTAAGTACATAGATAAGCCCAATACTTTTGTGAAACCTGCCATAGCTAACAGAGAAATCATCCTGGAATCTGGGGGAAGTAGAGTCGGCTTGTTTCTTGAAAAACCAGGTTCCCTGGCATGTGACCAGTTAATAACATGAACTTTGAAGTGATCTGGTCCAGCATAGTTGTCTTTTGAGGCGAACAAATAGGGTTGATGCGATTGCTCATCTCACCCCAACCACCTTAATGTTGCACAAGACGCTGCCCATGGGACTCCCTGGCGTAAGTGTCCTGGCCTACGTTGTTTGCATGCAATCAAAAGTGCATCCCTCACAGTTGGCCCAGTTTGGTAACTTTTCACGGCAGAACCCAGGAGGTAGATCGGGACCGGCGGGGTGCCCAGTTGGTACTCTGGCGGTAGTCTTCGAGTGCCTTTCCGGCCTGGGT


BAM OUTPUT

    m150521_125225_42141_c100722061910000001823149204301517_s1_p0/7108/ccs	4	*	0	255	*	*	0	0	AAGCTCAAGGATTGTTTAATGGCCACTGACAAAAGGTTACAACAGTTGCATCATTAACTGTGGCATGTAAAACCTGCCCCCTTCTGTTGATGCATAAAATCCACCAATAGAGGAAGATTCTTCCGTCAAGAATATAGGGTCTGGACTGATTACTATTTCTCGTAAATGCCGCAGCAGTTTCCAATCATAACAAACAAAAGGCCAAGCTTAGTAAGTACATAGATAAGCCCAATACTTTTGTGAAACCTGCCATAGCTAACAGAGAAATCATCCTGGAATCTGGGGGAAGTAGAGTCGGCTTGTTTCTTGAAAAACCAGGTTCCCTGGCATGTGACCAGTTAATAACATGAACTTTGAAGTGATCTGGTCCAGCATAGTTGTCTTTTGAGGCGAACAAATAGGGTTGATGCGATTGCTCATCTCACCCCAACCACCTTAATGTTGCACAAGACGCTGCCCATGGGACTCCCTGGCGTAAGTGTCCTGGCCTACGTTGTTTGCATGCAATCAAAAGTGCATCCCTCACAGTTGGCCCAGTTTGGTAACTTTTCACGGCAGAACCCAGGAGGTAGATCGGGACCGGCGGGGTGCCCAGTTGGTACTCTGGCGGTAGTCTTCGAGTGCCTTTCCGGCCTGGGT	/,))*)(+'+)(+)'++(,*'+',*)*)))&,,+'+'+))(,)*)'+))**)*(+(,)*))'+)**))&,,*',*)%,,,+'+(*)'+))*))**&,,+*',*',(,*)))'+(,))(+((+',)*)(,)(,*)*)&++))*'+))*))(+))*)'++(*))*',+*)',))*))*)'+*',(,*)**(,)',+)&,,+'+',(,))(+))*(,)*))**)))*(,)&,,(,*))&+++)))',+',*)',**)))*(,)*)))',+*)**',*'+(,*)*%+++*(,)*))))*)'+)(+)'++((+)%+++*',*'+'*&,,*'+)**))))',*)'+(,*(,)**)(,)'++)(,))))*)*'+)',*))**))'+)*(&+++))'+()(,)',+*)&++'+)962'261;$25%54&2'/"8($&%%'$$-04$5(%%233'$%:,%*33%2%:64%+<;#$.$%#/%011$%'#%$$&:6.<%66633'6$%942%56'31;%1##52/$0#$#"9%$$/%22%$#$%962%$##$$###"##$6-))',)*((+&++*',*',**)*))&,,*'+',)%,,,*)&++*)(+',**))))',)',**)*)(,))*)*)'+&,+'+','+)&,,-	RG:Z:9f2d31ee	np:i:0	pq:f:0.824774	rq:i:824	rs:B:i,2,0,0,0,0	sn:B:f,14.0804,8.38334,6.33849,7.13326	za:f:-4.27617	zm:i:7108	zs:B:f,-5.47436,-3.8087

Any chance we could fix this tomorrow?

**Comment by evolvedmicrobe** [comment]
Also, this template was refined by 99 applied mutations, far more than usual and likely leading to the slowdown.

**Comment by nlhepler** [comment]
So, I'm actually at a crossroads where I feel CCS is ill-defined for anything without at least a single full pass. I'm inclined to max(1, options.get("minPasses")) to deal with it, same as the old CCS--just because of the dilemma of 2-subread-neither-full-pass.

**Comment by nlhepler** [comment]
This is because the passthrough for those would generate 2 /ccs for a ZMW, which isn't supposed to happen.

**Comment by evolvedmicrobe** [comment]
Lance, let's change CCS so it is max(1, options.get("minPasses")) for now so we have a bug free tarball (I agree it's poorly defined, and so we should either handle it correctly or prevent it from happening).  Do you think we could push that today for @mseetin?

Let's then track down @etseng later and figure out what we can do to accommodate here.

**Comment by nlhepler** [comment]
Yea, I'm going to do that now. I'll even throw an error with minPasses < 1 just so users know.

**Comment by etseng** [comment]
Hi,

You forward to the wrong @etseng.
Sorry not let you know earlier.

Regards,
Eric

**Comment by nlhepler** [comment]
I've tests for edge-cases in the POA in c58f65043a600dd0764ff4bfaaedd729faeac908, going to close this issue.

**Comment by Magdoll** [comment]
Lance & Nigel: @magdoll is the one you are looking for...not etseng, sorry.

I'm not entirely comfortable with losing anything that is not a full-pass. A few thoughts:

(a) full-pass means both SMRTadapters are seen? this means some actually "full-length" (contains both 5' and 3' end of the cDNA primer) reads might actually get thrown out.

(b) Iso-Seq makes use of non-full-length reads as well to stack them up for increasing depth for polishing.

I'm more concerned about this effect on (a) than (b), unless I'm convinced that the reads from (a) would have sucked anyway --- it might be the case.

It might be good for me to go look at 0-pass vs 1-pass full-length CCS reads and ask: are 0-pass CCS reads any good? because if they are, I want them output by CCS. I don't want to add an extra script that "fishes out" the 0-pass subreads from primary. That would break the existing Iso-Seq pipeline as we would have to add that extra step (and it just seems unsanitary to me). I'd rather have a (maybe equally unsanitary option) of adding something in CCS that says "--0pass_anyway" that forces to output 0-pass primary reads....

Hope that makes sense.
