### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbccs#50]
Please add a CHANGELOG (or CHANGELOG.md) to keep track of changes; we should add an update for every "tagged" version

**Comment by evolvedmicrobe** [comment]
Added a python script to generate a changelog with 720a51d23f7fc3a .  Commits that should be included in the changelog should be made with a "**" in the message.  If present in the commit, the git message and commit date will become an entry in the change log.
