### ISSUE TITLE
--overwrite option?

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbccs#51]
Would it be possible to have a command-line option to overwrite existing files instead of existing with an error?  Not an essential feature, but would make testing easier.

(I could maybe implement this myself, but I thought I'd ask before diving into C++ code.)

**Comment by nlhepler** [comment]
I could add a -f flag, for --force. @evolvedmicrobe, thoughts?

**Comment by evolvedmicrobe** [comment]
@natechols if you want to submit a pull we'd accept.  Presumably unit/integration tests should always delete the output files though.

**Comment by nlhepler** [comment]
Fixed in 6c14501ffdc4099c11cedc83d099b126a311be4c
