### ISSUE TITLE
Feature Request:  Make QVsToASCII from Consensus.h public

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/pbccs#56]
Currently I've simply copied the code, though it might be better to have a shared set of public utility functions like this

**Comment by nlhepler** [comment]
I think pbbam has some utility functions like this. We should work with Derek on a unified data model.

**Comment by evolvedmicrobe** [comment]
The function is available to anyone who imports the header no? It's a pretty standard conversion that's available in most parsing libraries as well.

**Comment by bnbowman** [comment]
Nope - the anonymous namespace limits it to the local translation unit.  I agree with Lance on this, though - a couple such functions are fundamental enough that it's worth pushing them as low in the stack as possible, and PbBam is the logical place.

**Comment by evolvedmicrobe** [comment]
sounds like this is an issue for PbBAM, can I close this?

**Comment by evolvedmicrobe** [comment]
No response, assuming is pbbam issue
