### ISSUE TITLE
Feature Request: Strand-specific consensuses

### ISSUE THREAD

**Issue by verheytb** [PacificBiosciences/pbccs#58]
I've made my own program that I was hoping would be able to call the CCS for each strand separately, modified from [this code](https://github.com/PacificBiosciences/GenomicConsensus/blob/mini-ccs/rccs.py). However, the error rate is much higher than the CCS method in SMRT Portal, even after controlling for the number of subreads in each consensus.

Would it be possible to implement functionality that outputs separate consensuses for each strand?

**Comment by nlhepler** [comment]
Hi @verheytb! We can certainly do this, it's been a feature request even internally.

**Comment by verheytb** [comment]
Awesome, much appreciated!

**Comment by verheytb** [comment]
Any chance this will be out before October 30?

**Comment by nlhepler** [comment]
@verheytb, I cannot say for sure, but I *would expect* this feature to land in *this codebase* before then.

**Comment by evolvedmicrobe** [comment]
Looks like it may be strand specific time soon.

**Comment by verheytb** [comment]
Fantastic!

**Comment by evolvedmicrobe** [comment]
Strand specific consensus is now available by using the "--byStrand" option.  In general, this can be used to detect heteroduplex formation, which leads the forward and reverse strands to differ by a few SNPs.
