### ISSUE TITLE
Need to add tests and test data

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#6]

**Comment by dalexander** [comment]
I want to see this happen soon.  I don't feel comfortable with us making tweaks unless we have nightly Jenkins runs happening on a few datasets so we can guard against regressions.

**Comment by evolvedmicrobe** [comment]
We have internal bug 29722 designed to fill in our gap for large/integrative tests.  @natechols has most of the framework in place, so it's possible we can just include it with Jenkins.  Otherwise, we can generate some off-line CRAM tests.

**Comment by natechols** [comment]
I definitely encourage you to piggyback off the pbsmrtpipe CCS tests in Jenkins if possible - setting up whatever infrastructure is necessary is not a lot of work (for me), I just need to know what to test.  You can push Aaron to bump this up in priority if you feel it's urgent.

**Comment by evolvedmicrobe** [comment]
Lance's likelihood tests are awesome, we could use some more integration tests, but I no longer consider this an open issue.
