### ISSUE TITLE
fix bax2bam usage instruction on README

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbccs#63]
It doesn't work---bax2bam doesn't understand bas.h5 files

It might work in the future with Brett's changes, but we should be providing documentation that works for the preview customers.

**Comment by nlhepler** [comment]
Fixed in adc68444ac680243299e3609ef4b73c3966810b8

**Comment by bnbowman** [comment]
Did you test the proposed README instructions?  Because Bas.H5 support works for me from the nightly build, and if Bas.H5 support isn't working for anyone else I'd like to know...

**Comment by nlhepler** [comment]
The tarball we shipped to some customers doesn't have the bas.h5 support in it, so until then we'll go with the bax.h5 instructions.
