### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbccs#65]
I am not an expert on CMake, 
I fixed some minor problems in your cmake file, now having this one:

~/remoteh/src/buildccs$ cmake ../pbccs
You have called ADD_LIBRARY for library pbccs without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:22 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

**Comment by nlhepler** [comment]
@kemin711,

Without knowing your changes, I cannot hope help you debug your issue. Could you publish them to a place on github? And may I ask, what minor problems were you having?

**Comment by kemin711** [comment]
20 # libpbccs.a
 21 add_library(pbccs STATIC ${PacBioCCS_CPP} ${PacBioCCS_H})
/src/CMakeLists.txt 
22 set_target_properties(pbccs PROPERTIES
 23     ARCHIVE_OUTPUT_DIRECTORY ${PacBioCCS_LibDir}
 24 )

Line 23 one of the two variables are undefined:
You have called ADD_LIBRARY for library pbccs without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:22 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

Will this be enough.

**Comment by kemin711** [comment]
1 cmake_minimum_required(VERSION 3.3)

I have add this line to the top of the file to suppress warnings

**Comment by nlhepler** [comment]
@kemin711, this is indicating that there are no files in either ${PacBioCCS_CPP} or ${PacBioCCS_H}, which were fetched using FILE(GLOB_RECURSE ...) into the src/ and include/ directories, respectively. Do you have a full and complete checkout?

**Comment by nlhepler** [comment]
So, as you've noticed, you'll need both htslib and the pbbam modules. I recommend looking at the circle.yaml file to see how we build it there.

Additionally, building pbccs locally won't be too useful at the moment. The ccs application only takes PacBio BAM files, and the conversion tool for ba{sx}.h5s is bax2bam (#62), hasn't been made available on github yet. We're working on this, and will have wiki instructions for building and running these tools when they are both available in source form.

**Comment by annalenakeller** [comment]
@nlhepler, can you estimate when pbccs will be made available on github? I saw the SMRT Analyses 3.0 preview and am really looking forward to using the new CCS program!

**Comment by nlhepler** [comment]
@annalenakeller, the source is already here, though it does require some effort to build. =/ We're working on getting the open source build process into a smoother state, as well as some instructions to facilitate (building native binaries is always nightmarishly complicated..). Unfortunately, I don't have an ETA for the completion of that work. As for pre-compiled binaries, I cannot say when exactly, except perhaps to say "Soon." =)

**Comment by annalenakeller** [comment]
Thank you @nlhepler for the update. You mentioned in your previous post that bax2bam isn't available yet (#62). My question was more related to that issue, sorry for not being very clear there. We should get pbccs to work as soon as the source code of bax2bam is made available. Could we get access to that tool any time "sooner" ;) ? We sequenced several datasets enriched for resistance genes. The data is highly repetitive and might contain PCR introduced errors. If we could improve accuracy and remove errors in the CCS reads with your new method, we expect a quite substantial improvement of mappings, assemblies and other analyses.

**Comment by armintoepfer** [comment]
Even though a pbccs binary from source does not help you without bax2bam, you can build it with this script: https://gist.github.com/armintoepfer/50f6e13e19fb9527fa18

**Comment by dalexander** [comment]
@annalenakeller, you should contact Tzvetana if you are interested in getting pre-release access to our tools.    (tkerelska@pacificbiosciences.com)
