### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbccs#67]
On a different system:
 
add_subdirectory given source
  "$HOME/src/pacbio/pbccs/../../../software/smrtanalysis/bioinformatics/staging/PostPrimary/pbbam"
  which is not an existing directory.

I wonder that I need to download other source directory?
Also I may need the pbbam module

**Comment by nlhepler** [comment]
Yes, you'll need the pbbam module. I suggest you take a look at the circle.yaml file to see how we build it for circleci.

**Comment by nlhepler** [comment]
Also, pbbam will require htslib
