### ISSUE TITLE
BAM parsing errors cause crashes

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#79]
Right now any error inside the BAM file causes a nasty looking crash.  We should handle these more gracefully.

**Comment by evolvedmicrobe** [comment]
Referencing internal bug 28284, we won't reinvent the wheel in this code.

**Comment by nlhepler** [comment]
This is a pbbam bug, referenced internally. Closing here.

**Comment by evolvedmicrobe** [comment]
It's two bugs, pbbam needs to implement this feature (that's the internal one), and then we need to use it (that's this one), I like leaving this as a reminder that this hasn't been taken care of yet, though we have some work arounds and checks on file existence in place while we wait.

**Comment by nlhepler** [comment]
if pbbam is crashing on malformed data, it's a bug there in the parsing libraries and not a feature that needs to be enabled here. There won't be anything for us to turn on, or there shouldn't be. But we can leave this open if you prefer.

**Comment by evolvedmicrobe** [comment]
The internal bug is a feature request to have a method to check if a BAM is valid, once that method exists we will call it here and report the error.

**Comment by evolvedmicrobe** [comment]
A call to:

     BamFile f(fn);

Apparently will now throw if we have a file that is easily identifiable as bad (problems in header, existence EOF, etc.).  We bubble this message through so this is resolved now.
