### ISSUE TITLE
Investigate Relaxing SNR Filters

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#86]
Right now we filter out Minimum SNR < 4, which results in ~10% yield loss.  However, with the new model we haven't established there are any problems with data below this range if quality filtering is applied, and with many passes we can likely recover some useful information.

**Comment by nlhepler** [comment]
Definitely worthy of investigation

**Comment by evolvedmicrobe** [comment]
Looked a bit at this today by evaluating three SMRTCells worth of data.

First, for these SMRT cells between 5.5%-11.5% of the data had a Min SNR < 4, so this represents the range of the maximum yield increase we could obtain by lowering this threshold.  If we only consider reads with RQ > QV30, we have between 5% - 8.5% of reads that could be added to the yield.

![minimumsnr](https://cloud.githubusercontent.com/assets/1330626/11258457/09ab9c6c-8e0e-11e5-8b30-23e693b239d7.png)

The MinSNR threshold actually had surprisingly little effect on the mean accuracy once QV filtering is taken into account (see below), and it seems the yield is changing more than the accuracy. 

![accuracyvsthreshold](https://cloud.githubusercontent.com/assets/1330626/11258458/10b9b3ae-8e0e-11e5-9a28-a1992b73d23c.png)


Lower SNR data clearly has a worse NP versus Error rate curve (see below), but the difference is not as profound for reads with high RQ, suggesting that filtering may allow you to increase the yield without sacrificing the accuracy by only taking the high quality low SNR data.

![accuracyvsnp](https://cloud.githubusercontent.com/assets/1330626/11258466/20446ef4-8e0e-11e5-91be-dc96fdc3a077.png)



A new default MinSNR of 3.75 would be a reasonable incremental change. For these SMRTCells, lowering the Minimum SNR from 4 to 3.75 would a 1.5% to 3% increase in the yield of RQ >= 0.999 reads per SMRTcell. Importantly, it appears that the RQ value is still a useful predictor for this data, and you can still predict and exclude the total errors using it.


![obsvexpected](https://cloud.githubusercontent.com/assets/1330626/11258471/2ab11e78-8e0e-11e5-99de-f2be6c408d58.png)

So, my feeling is you get a yield increase if you use a 3.75 default minimum, and if you use RQ filtering, you can still maintain quality.  I therefore propose we drop the criteria to 3.75 from 4.  Thoughts?

**Comment by mseetin** [comment]
Yeah, I think that will be a nice change.  Thanks for taking a look.

**Comment by nlhepler** [comment]
+1

**Comment by evolvedmicrobe** [comment]
And the Aye's have it!  Just committed a change to make 3.75 the default.

For clarity, note that this doesn't mean SNR has no effect, just that like the Z-score, above a minimum it has a very mild effect, and if you know the RQ/QUAL value than there is little useful additional information to be gained from the SNR or Z-Score.
