### ISSUE TITLE
Fix NaN Option for MinZScore

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#87]
--minZScore=NaN works on some platforms but not others, the joys of C++.  Need to adjust the code to not fault on ubuntu.

**Comment by nlhepler** [comment]
seriously?! wtf

**Comment by evolvedmicrobe** [comment]
Yeah, totally lame.  https://github.com/PacificBiosciences/pbccs/commit/4174668c02e810af20c37c806be59a0a7eee3516
