### ISSUE TITLE
CCS BAM files not part of a PacBio BAM specification

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#91]
The CCS BAM file format is documented by the README for this repository.  However there is another BAM specification for PacBio:

https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst

But this does not fully or adequately describe CCS files (the RQ and QUAL fields being a good example).

We should decide if we want to have redundant specifications (one here, one there), and update whatever we want to keep appropriately.

**Comment by nlhepler** [comment]
Actually, it does. The spec says the rq field encodes the expected accuracy and that the QUAL field is present for the CCS. So we follow the spec. If the spec needs more descriptive text, the issue belongs there.
