### ISSUE TITLE
CCS2 throws unexpected exception

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#96]
Report from the field, see email on 12/7/2015 from mseetin.

**Comment by nlhepler** [comment]
This was an unhandled AlphaBetaMismatch from Polish, which we now catch appropriately. Still need to figure out why we're getting them, however.

**Comment by evolvedmicrobe** [comment]
This indicates a mathematical error and is not yet diagnosed or handled correctly, I wasn't even aware we tried to band aid it with a catch statement.

**Comment by evolvedmicrobe** [comment]
Actually, I might be totally off base here, are we referring to: https://github.com/PacificBiosciences/ConsensusCore2/pull/7 or is this unrelated?

**Comment by nlhepler** [comment]
This is unrelated. This is "Unexpected exception" warnings being thrown in the Polish step, which we know happen due to possible issues in CC2. You fixed this in 5c877533d1200a95f94cfacd1a63ff1e8b01a10f.

**Comment by evolvedmicrobe** [comment]
doh! Sorry for reopening.
